# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Photopon' do
pod 'Parse', '~> 1.7'
pod 'ParseUI'
pod 'FontAwesome'
pod 'PubNub'
pod 'SDWebImage'
pod 'IQKeyboardManager'
end

target 'PhotoponTests' do

end

